modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="tfc_aerospace"
version="1.0.2"
displayName="TFC-aerospace"
credits="Thanks to TFC and tfc Ambiental."
displayURL="https://www.curseforge.com/minecraft/mc-mods/tfc-aerospace"
authors="Fernando, MCreator"

[[dependencies.tfc_aerospace]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.tfc_aerospace]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

